{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Chart.Name }}-cert
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: {{ .Values.service.externalPort }}
          - path: /static
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.nginxServiceName }}
                port:
                  number: 80
          - path: /assets
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.nginxServiceName }}
                port:
                  number: 80
{{- end }}