apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
  type: {{ .Values.service.type }}
