export const SET_SYSTEM_CONFIGURATIONS = 'SET_SYSTEM_CONFIGURATIONS';
export const SWITCH_DARK_MODE = 'SWITCH_DARK_MODE';
export const SET_MOBILE_PLATOFORM = 'SET_MOBILE_PLATOFORM';
export const SET_GLOBAL_ALERT_DIALOG = 'SET_GLOBAL_ALERT_DIALOG';
export const USER = 'USER';
export const USER_FAVORITES_STANDS = 'USER_FAVORITES_STANDS';
export const USER_FAVORITES_ADD_STAND = 'USER_FAVORITES_ADD_STAND';
export const USER_FAVORITES_DELETE_STAND = 'USER_FAVORITES_DELETE_STAND';
export const USER_FAVORITES_ITEMS = 'USER_FAVORITES_ITEMS';
export const USER_FAVORITES_ADD_ITEM = 'USER_FAVORITES_ADD_ITEM';
export const USER_FAVORITES_DELETE_ITEM = 'USER_FAVORITES_DELETE_ITEM';
export const USER_CART = 'USER_CART';
export const USER_CART_ADD_ITEM = 'USER_CART_ADD_ITEM';
export const USER_CART_UPDATE_ITEM = 'USER_CART_UPDATE_ITEM';
export const USER_CART_DELETE_ITEM = 'USER_CART_DELETE_ITEM';
export const USER_ORDERS = 'USER_ORDERS';
export const FILE_PREFIX = {
  ANDROID: 'file:///android_asset/www'
};
export const CATEGORY_DATA = 'CATEGORY_DATA';
export const STAND_DATA = 'STAND_DATA';
export const UPDATE_STAND_AVERAGE_RATING = 'UPDATE_STAND_AVERAGE_RATING';
export const EXPO_DATA = 'EXPO_DATA';
export const GROUP_DATA = 'GROUP_DATA';
